// Generated by ReScript, PLEASE EDIT WITH CARE

import * as ModTs from "https://deno.land/std@0.123.0/log/mod.ts";
import * as ServerTs from "https://deno.land/std@0.123.0/http/server.ts";

ModTs.info("serving project on http://0.0.0.0:2112");

ServerTs.serve((function (_req) {
        return Promise.resolve(new Response("Hello, world!"));
      }), {
      port: 2112
    });

export {
  
}
/*  Not a pure module */
