// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_option from "rescript/lib/es6/caml_option.js";

function to_array(t) {
  var aux = function (acc) {
    return t.next().then(function (result) {
                var el = result.value;
                if (el !== undefined) {
                  return aux(acc.concat([Caml_option.valFromOption(el)]));
                } else {
                  return Promise.resolve(acc);
                }
              });
  };
  return aux([]);
}

export {
  to_array ,
  
}
/* No side effect */
