// Generated by ReScript, PLEASE EDIT WITH CARE


var $$Uint8Array = {};

var Controller = {};

var Readable_stream = {
  Controller: Controller
};

var Async = {};

var Text_encoder = {};

var $$File = {};

var Fs = {};

var Io = {};

var Console = {};

var Path = {};

var Log = {};

var Args = {};

var Flags = {
  Args: Args
};

var $$URL = {};

var $$Headers = {};

var $$Request = {};

var $$Response = {};

var Http = {
  $$Headers: $$Headers,
  $$Request: $$Request,
  $$Response: $$Response
};

var $$Promise;

export {
  $$Promise ,
  $$Uint8Array ,
  Readable_stream ,
  Async ,
  Text_encoder ,
  $$File ,
  Fs ,
  Io ,
  Console ,
  Path ,
  Log ,
  Flags ,
  $$URL ,
  Http ,
  
}
/* No side effect */
