// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Caml_option = require("rescript/lib/js/caml_option.js");

function to_array(t) {
  var aux = function (acc) {
    return t.next().then(function (result) {
                var el = result.value;
                if (el !== undefined) {
                  return aux(acc.concat([Caml_option.valFromOption(el)]));
                } else {
                  return Promise.resolve(acc);
                }
              });
  };
  return aux([]);
}

exports.to_array = to_array;
/* No side effect */
