// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var $$Uint8Array = {};

var Controller = {};

var Readable_stream = {
  Controller: Controller
};

var Async = {};

var Text_encoder = {};

var $$File = {};

var Fs = {};

var Io = {};

var Console = {};

var Path = {};

var Log = {};

var Args = {};

var Flags = {
  Args: Args
};

var $$URL = {};

var $$Headers = {};

var $$Request = {};

var $$Response = {};

var Http = {
  $$Headers: $$Headers,
  $$Request: $$Request,
  $$Response: $$Response
};

var $$Promise;

exports.$$Promise = $$Promise;
exports.$$Uint8Array = $$Uint8Array;
exports.Readable_stream = Readable_stream;
exports.Async = Async;
exports.Text_encoder = Text_encoder;
exports.$$File = $$File;
exports.Fs = Fs;
exports.Io = Io;
exports.Console = Console;
exports.Path = Path;
exports.Log = Log;
exports.Flags = Flags;
exports.$$URL = $$URL;
exports.Http = Http;
/* No side effect */
